DEFAULT_REVIEW_PAGE_SIZE = 20
MAX_REVIEW_PAGE_SIZE = 100

DEFAULT_REVIEW_MODE = 'standard'
DEFAULT_REVIEW_ORDERING = '-published_date'
DEFAULT_PROVIDER_ORDER = ('2gis', 'yandex', 'google', 'vlru')
MAX_INTERLEAVE_SIZE = 100
