# Generated by Django 5.2.2 on 2026-07-28 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0025_alter_video_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='BranchProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('2gis', '2GIS'), ('vlru', 'VL.RU'), ('yandex', 'Yandex'), ('google', 'Google')], max_length=30)),
                ('source_url', models.URLField(max_length=1500)),
                ('external_place_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_providers', to='common_parser.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_rating_avg', models.FloatField(blank=True, null=True)),
                ('last_parse_date', models.DateTimeField(blank=True, null=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='common_parser.branchprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('other', 'Другое')], max_length=50)),
                ('url', models.URLField(max_length=1500)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='common_parser.review')),
            ],
        ),
        migrations.AddConstraint(
            model_name='branchprovider',
            constraint=models.UniqueConstraint(fields=('branch', 'provider', 'source_url'), name='unique_branch_provider_source_url'),
        ),
    ]
