# Generated by Django 5.2.2 on 2026-07-29 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0026_alter_video_preview_branchprovider_providerstat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchipmapping',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='playlistipmapping',
            name='playlist',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='parse_date',
            new_name='last_parse_time',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='avatar',
            new_name='author_avatar_url',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='preview',
            new_name='preview_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='google_map_url',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='google_parse_date',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='google_review_avg',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='google_review_count',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='twogis_map_url',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='twogis_parse_date',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='twogis_review_avg',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='twogis_review_count',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='vlru_org_id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='vlru_parse_date',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='vlru_review_avg',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='vlru_review_count',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='vlru_url',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='yandex_map_url',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='yandex_parse_date',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='yandex_review_avg',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='yandex_review_count',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='count',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='review',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='external_playlist_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='common_parser.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='source_url',
            field=models.URLField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='content_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='external_review_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='provider',
            field=models.CharField(choices=[('youtube', 'Ютуб'), ('vk', 'Вк')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='common_parser.branchprovider'),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_url',
            field=models.URLField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(max_length=1500),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('organization', 'source_url'), name='unique_organization_source_url'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('external_review_id__isnull', False)), fields=('provider', 'external_review_id'), name='unique_provider_external_review_id_not_null'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('provider', 'content_hash'), name='unique_provider_content_hash'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('playlist', 'external_id'), name='unique_playlist_external_id_not_null'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('playlist', 'url'), name='unique_playlist_url'),
        ),
        migrations.DeleteModel(
            name='BranchIPMapping',
        ),
        migrations.DeleteModel(
            name='PlaylistIPMapping',
        ),
    ]
