# Generated by Django 5.2.2 on 2026-07-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0027_remove_branchipmapping_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchprovider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchprovider',
            name='last_parse_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchprovider',
            name='next_parse_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='branchprovider',
            name='parse_frequency',
            field=models.CharField(choices=[('hourly', 'Раз в час'), ('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='weekly', max_length=20),
        ),
    ]
