# Generated by Django 5.2.2 on 2026-08-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0028_branchprovider_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchprovider',
            name='next_parse_date',
        ),
        migrations.RemoveField(
            model_name='branchprovider',
            name='parse_frequency',
        ),
    ]
